#include <H5Ppublic.h>

// The exported value
int OBJECT_CREATE, FILE_CREATE, FILE_ACCESS, DATASET_CREATE,
  DATASET_ACCESS, DATASET_XFER, FILE_MOUNT, GROUP_CREATE,
  GROUP_ACCESS, DATATYPE_CREATE, DATATYPE_ACCESS, STRING_CREATE,
  ATTRIBUTE_CREATE, OBJECT_COPY, LINK_CREATE, LINK_ACCESS;
// Initialises values
void inline init() {
  OBJECT_CREATE = H5P_OBJECT_CREATE;
  FILE_CREATE = H5P_FILE_CREATE;
  FILE_ACCESS = H5P_FILE_ACCESS;
  DATASET_CREATE = H5P_DATASET_CREATE;
  DATASET_ACCESS = H5P_DATASET_ACCESS;
  DATASET_XFER = H5P_DATASET_XFER;
  FILE_MOUNT = H5P_FILE_MOUNT;
  GROUP_CREATE = H5P_GROUP_CREATE;
  GROUP_ACCESS = H5P_GROUP_ACCESS;
  DATATYPE_CREATE = H5P_DATATYPE_CREATE;
  DATATYPE_ACCESS = H5P_DATATYPE_ACCESS;
  STRING_CREATE = H5P_STRING_CREATE;
  ATTRIBUTE_CREATE = H5P_ATTRIBUTE_CREATE;
  OBJECT_COPY = H5P_OBJECT_COPY;
  LINK_CREATE = H5P_LINK_CREATE;
  LINK_ACCESS = H5P_LINK_ACCESS;
}
